version: '3'
services:
  notebook:
    container_name: python_notebook
    labels:
      description: Jupyter Notebooks
      name: jupyter notebook
    ports:
      - "8888:8888"
    volumes:
      - ~/Documents/jupyter_notebooks:/usr/src/app/jupyter_notebooks
    build: .